export const AVAILABLE_JOBS_FETCH_REQUESTED = "AVAILABLE_JOBS_FETCH_REQUESTED";
export const AVAILABLE_JOBS_FETCH_SUCCEEDED = "AVAILABLE_JOBS_FETCH_SUCCEEDED";
export const AVAILABLE_JOBS_FETCH_FAILED = "AVAILABLE_JOBS_FETCH_FAILED";

export const APPLIED_JOBS_FETCH_REQUESTED = "APPLIED_JOBS_FETCH_REQUESTED";
export const APPLIED_JOBS_FETCH_SUCCEEDED = "APPLIED_JOBS_FETCH_SUCCEEDED";
export const APPLIED_JOBS_FETCH_FAILED = "APPLIED_JOBS_FETCH_FAILED";

export const APPLY_JOB_REQUESTED = "APPLY_JOB_REQUESTED";
export const APPLY_JOB_SUCCEEDED = "APPLY_JOB_SUCCEEDED";
export const APPLY_JOB_FAILED = "APPLY_JOB_FAILED";

export const RESET_CANDIDATE_DATA = "RESET_CANDIDATE_DATA";
