export const POSTED_JOBS_FETCH_REQUESTED = "POSTED_JOBS_FETCH_REQUESTED";
export const POSTED_JOBS_FETCH_SUCCEEDED = "POSTED_JOBS_FETCH_SUCCEEDED";
export const POSTED_JOBS_FETCH_FAILED = "POSTED_JOBS_FETCH_FAILED";

export const JOB_APPLICANTS_FETCH_REQUESTED = "JOB_APPLICANTS_FETCH_REQUESTED";
export const JOB_APPLICANTS_FETCH_SUCCEEDED = "JOB_APPLICANTS_FETCH_SUCCEEDED";
export const JOB_APPLICANTS_FETCH_FAILED = "JOB_APPLICANTS_FETCH_FAILED";

export const POST_JOB_REQUESTED = "POST_JOB_REQUESTED";
export const POST_JOB_SUCCEEDED = "POST_JOB_SUCCEEDED";
export const POST_JOB_FAILED = "POST_JOB_FAILED";

export const RESET_RECRUITER_DATA = "";
